#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Renders the installer's braille logo from the app icon into
# scripts/lib/installer/logo.sh. Needs chafa and python3 with Pillow.
# Usage: scripts/render-installer-logo.sh
set -euo pipefail

root=$(cd "$(dirname "$0")/.." && pwd)
src="$root/assets/images/helix-icon-256.png"
out="$root/scripts/lib/installer/logo.sh"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

python3 -c 'import sys; from PIL import Image; im = Image.open(sys.argv[1]); im.crop(im.getbbox()).save(sys.argv[2])' "$src" "$tmp/ribbon.png"

render() { # colors
    chafa --format symbols --size 26x10 --symbols braille --colors "$1" --polite on --animate off "$tmp/ribbon.png"
}

{
    printf '#!/bin/sh\n# SPDX-License-Identifier: GPL-3.0-or-later\n'
    printf '# Generated by scripts/render-installer-logo.sh from assets/images/helix-icon-256.png.\n'
    printf '# Do not edit; re-run the script.\n\n'
    printf '_logo_art() {\n    case "$1" in\n'
    for c in 256 16; do
        printf '        %s) cat <<'"'"'HELIX_LOGO_EOF'"'"'\n' "$c"
        render "$c"
        printf '\nHELIX_LOGO_EOF\n            ;;\n'
    done
    printf '    esac\n}\n'
    cat <<'SH'

# Logotype colors match the wordmark: Helix in blue, Screen as a red to
# orange ramp. 16-color terminals get the nearest ANSI colors.
_logotype() {
    if [ "$UI_COLOR" = 256 ]; then
        printf '\033[1;38;5;33mHelix\033[38;5;197mSc\033[38;5;203mre\033[38;5;209me\033[38;5;214mn\033[0m'
    elif [ "$UI_COLOR" = 16 ]; then
        printf '\033[1;34mHelix\033[1;31mScr\033[1;33meen\033[0m'
    else
        printf 'HelixScreen'
    fi
}

print_banner() { # version channel
    if [ "$UI_TTY" != 1 ]; then
        printf 'HelixScreen installer %s (%s)\n' "$1" "$2" >&2
        return 0
    fi
    _pb_sub="$(printf '%b%s · %s channel%b' "$DIM" "$1" "$2" "$NC")"
    [ "$UI_UTF8" = 1 ] || _pb_sub="$(printf '%b%s (%s channel)%b' "$DIM" "$1" "$2" "$NC")"
    printf '\n' >&2
    if [ "$UI_UTF8" = 1 ] && [ "$UI_COLOR" != 0 ]; then
        _pb_i=0
        _logo_art "$UI_COLOR" | while IFS= read -r _pb_line; do
            _pb_i=$((_pb_i + 1))
            case $_pb_i in
                5) printf '  %s\033[0m   %s\n' "$_pb_line" "$(_logotype)" ;;
                6) printf '  %s\033[0m   %s\n' "$_pb_line" "$_pb_sub" ;;
                *) printf '  %s\033[0m\n' "$_pb_line" ;;
            esac
        done >&2
    else
        printf '  %s\n  %s\n' "$(_logotype)" "$_pb_sub" >&2
    fi
    printf '\n' >&2
}
SH
} > "$out"
echo "wrote $out"
