// Copyright (C) 2025-2026 356C LLC
// SPDX-License-Identifier: GPL-3.0-or-later

/**
 * @file test_mock_gcode_dispatch.cpp
 * @brief Pins MoonrakerClientMock::gcode_script's observable behaviour per command
 *
 * Every row runs a script sequence on a fresh mock and compares one line of
 * snapshot (return code, error latch, every notification dispatched, and the
 * state getters) against the recorded text. Rows cover each recognised command,
 * near-misses that must NOT match, and inputs where two matchers fire on the
 * same line: substring matching means one command can shadow, or run alongside,
 * another, and that ordering is part of the contract.
 *
 * Commands whose effects land on the simulation thread or an lv_timer
 * (restarts, print control, calibration timers, vendor feeder state machines)
 * pin the synchronous half only: return code, error latch and state getters.
 */

#include "../helix_test_fixture.h"
#include "../lvgl_test_fixture.h"
#include "../test_helpers/scoped_env.h"
#include "moonraker_client_mock.h"

#include <sstream>
#include <string>
#include <vector>

#include "../catch_amalgamated.hpp"
#include "hv/json.hpp"

using namespace helix;
using json = nlohmann::json;
using PT = MoonrakerClientMock::PrinterType;

namespace {

struct DispatchCase {
    PT type;
    const char* ams;  ///< HELIX_MOCK_AMS (nullptr = unset)
    const char* objs; ///< HELIX_MOCK_OBJECTS (nullptr = unset)
    bool sync;        ///< true: notifications are dispatched on the calling thread
    std::vector<std::string> scripts;
    const char* expected;
};

// Mesh heights are randomised per calibration; only their shape is pinned.
std::string mesh_shape(const json& matrix) {
    if (!matrix.is_array() || matrix.empty()) {
        return "0x0";
    }
    return std::to_string(matrix.size()) + "x" + std::to_string(matrix[0].size());
}

std::string frame_text(json n) {
    if (n.contains("params") && n["params"].is_array() && !n["params"].empty() &&
        n["params"][0].is_object() && n["params"][0].contains("bed_mesh")) {
        json& mesh = n["params"][0]["bed_mesh"];
        if (mesh.contains("probed_matrix")) {
            mesh["probed_matrix"] = mesh_shape(mesh["probed_matrix"]);
        }
        if (mesh.contains("profiles")) {
            for (auto& [name, profile] : mesh["profiles"].items()) {
                profile["points"] = mesh_shape(profile["points"]);
            }
        }
    }
    return n.dump();
}

std::string snapshot(const DispatchCase& c) {
    ScopedEnv ams_env("HELIX_MOCK_AMS", c.ams);
    ScopedEnv objs_env("HELIX_MOCK_OBJECTS", c.objs);

    MoonrakerClientMock mock(c.type);
    std::vector<std::string> frames;
    mock.register_notify_update([&frames](const json& n) { frames.push_back(frame_text(n)); });
    mock.register_method_callback("notify_gcode_response", "pin",
                                  [&frames](const json& n) { frames.push_back(frame_text(n)); });

    std::ostringstream out;
    for (const auto& script : c.scripts) {
        frames.clear();
        const int rc = mock.gcode_script(script);
        out << script << " => rc=" << rc << " err=[" << mock.get_last_gcode_error() << "]";
        if (c.sync) {
            for (const auto& f : frames) {
                out << " {" << f << "}";
            }
        }
        out << " ;; ";
    }
    out << "klippy=" << static_cast<int>(mock.get_klippy_state())
        << " phase=" << static_cast<int>(mock.get_print_phase()) << " excluded=";
    for (const auto& name : mock.get_excluded_objects()) {
        out << name << ",";
    }
    out << " mesh=" << mock.get_active_bed_mesh().name << " profiles=";
    for (const auto& p : mock.get_bed_mesh_profiles()) {
        out << p << ",";
    }
    out << " tool=" << mock.get_active_gcode_tool();
    return out.str();
}

const std::vector<DispatchCase>& cases() {
    static const std::vector<DispatchCase> rows =
        {
            // --- thermal ---------------------------------------------------------
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"M104 S200"},
             R"G(M104 S200 => rc=0 err=[] {{"method":"notify_status_update","params":[{"extruder":{"target":200.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"M109 S210"},
             R"G(M109 S210 => rc=0 err=[] {{"method":"notify_status_update","params":[{"extruder":{"target":210.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"M140 S60"},
             R"G(M140 S60 => rc=0 err=[] {{"method":"notify_status_update","params":[{"heater_bed":{"target":60.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"M190 S55"},
             R"G(M190 S55 => rc=0 err=[] {{"method":"notify_status_update","params":[{"heater_bed":{"target":55.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"M104"},
             R"G(M104 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"m104 S180"},
             R"G(m104 S180 => rc=0 err=[] {{"method":"notify_status_update","params":[{"extruder":{"target":180.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"M104 S100 M140 S60"},
             R"G(M104 S100 M140 S60 => rc=0 err=[] {{"method":"notify_status_update","params":[{"extruder":{"target":100.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"M140 S60 M104 S100"},
             R"G(M140 S60 M104 S100 => rc=0 err=[] {{"method":"notify_status_update","params":[{"extruder":{"target":60.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_HEATER_TEMPERATURE HEATER=extruder TARGET=205"},
             R"G(SET_HEATER_TEMPERATURE HEATER=extruder TARGET=205 => rc=0 err=[] {{"method":"notify_status_update","params":[{"extruder":{"target":205.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_HEATER_TEMPERATURE HEATER=heater_bed TARGET=65"},
             R"G(SET_HEATER_TEMPERATURE HEATER=heater_bed TARGET=65 => rc=0 err=[] {{"method":"notify_status_update","params":[{"heater_bed":{"target":65.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_HEATER_TEMPERATURE HEATER=chamber TARGET=40"},
             R"G(SET_HEATER_TEMPERATURE HEATER=chamber TARGET=40 => rc=0 err=[] {{"method":"notify_status_update","params":[{"heater_generic chamber":{"target":40.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_HEATER_TEMPERATURE HEATER=heater_generic chamber TARGET=40"},
             R"G(SET_HEATER_TEMPERATURE HEATER=heater_generic chamber TARGET=40 => rc=1 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_HEATER_TEMPERATURE HEATER=nonexistent TARGET=40"},
             R"G(SET_HEATER_TEMPERATURE HEATER=nonexistent TARGET=40 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_HEATER_TEMPERATURE HEATER=extruder"},
             R"G(SET_HEATER_TEMPERATURE HEATER=extruder => rc=0 err=[] {{"method":"notify_status_update","params":[{"extruder":{"target":0.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_HEATER_TEMPERATURE HEATER=extruder TARGET=200 M140 S50"},
             R"G(SET_HEATER_TEMPERATURE HEATER=extruder TARGET=200 M140 S50 => rc=0 err=[] {{"method":"notify_status_update","params":[{"extruder":{"target":200.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_TEMPERATURE_FAN_TARGET TEMPERATURE_FAN=chamber TARGET=45"},
             R"G(SET_TEMPERATURE_FAN_TARGET TEMPERATURE_FAN=chamber TARGET=45 => rc=0 err=[] {{"method":"notify_status_update","params":[{"heater_generic chamber":{"target":45.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_TEMPERATURE_FAN_TARGET TARGET=45 SET_PIN PIN=x"},
             R"G(SET_TEMPERATURE_FAN_TARGET TARGET=45 SET_PIN PIN=x => rc=0 err=[] {{"method":"notify_status_update","params":[{"heater_generic chamber":{"target":45.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"PANDA_BREATH_DRY_START TEMP=60 HOURS=20"},
             R"G(PANDA_BREATH_DRY_START TEMP=60 HOURS=20 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"PANDA_BREATH_DRY_START"},
             R"G(PANDA_BREATH_DRY_START => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"PANDA_BREATH_DRY_START TEMP=60", "PANDA_BREATH_DRY_STOP"},
             R"G(PANDA_BREATH_DRY_START TEMP=60 => rc=0 err=[] ;; PANDA_BREATH_DRY_STOP => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"PANDA_BREATH_DRY_START M140 S50"},
             R"G(PANDA_BREATH_DRY_START M140 S50 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             "heater_generic dragonbreath dragonbreath output_pin dragonbreath_filter",
             true,
             {"SET_PIN PIN=dragonbreath_filter VALUE=1"},
             R"G(SET_PIN PIN=dragonbreath_filter VALUE=1 => rc=0 err=[] {{"method":"notify_status_update","params":[{"output_pin dragonbreath_filter":{"value":1.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             "heater_generic dragonbreath dragonbreath output_pin dragonbreath_filter",
             true,
             {"SET_PIN PIN=other VALUE=1"},
             R"G(SET_PIN PIN=other VALUE=1 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             "heater_generic dragonbreath dragonbreath output_pin dragonbreath_filter",
             true,
             {"SET_PIN PIN=dragonbreath_filter VALUE=0.5 M104 S99"},
             R"G(SET_PIN PIN=dragonbreath_filter VALUE=0.5 M104 S99 => rc=0 err=[] {{"method":"notify_status_update","params":[{"output_pin dragonbreath_filter":{"value":0.5}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             "heater_generic dragonbreath dragonbreath output_pin dragonbreath_filter",
             true,
             {"SET_HEATER_TEMPERATURE HEATER=dragonbreath TARGET=45"},
             R"G(SET_HEATER_TEMPERATURE HEATER=dragonbreath TARGET=45 => rc=0 err=[] {{"method":"notify_status_update","params":[{"heater_generic dragonbreath":{"target":45.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_PIN PIN=x VALUE=1"},
             R"G(SET_PIN PIN=x VALUE=1 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},

            // --- display message -------------------------------------------------
            {PT::VORON_24, nullptr, nullptr, true, {"M117 hello"}, R"G(M117 hello => rc=0 err=[] {{"method":"notify_status_update","params":[{"display_status":{"message":"hello"}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"M117"},
             R"G(M117 => rc=0 err=[] {{"method":"notify_status_update","params":[{"display_status":{"message":""}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"M117  hello"},
             R"G(M117  hello => rc=0 err=[] {{"method":"notify_status_update","params":[{"display_status":{"message":" hello"}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"M117   "},
             R"G(M117    => rc=0 err=[] {{"method":"notify_status_update","params":[{"display_status":{"message":""}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"M117hello"},
             R"G(M117hello => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"m117 lower"},
             R"G(m117 lower => rc=0 err=[] {{"method":"notify_status_update","params":[{"display_status":{"message":"lower"}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"M117 homing G28"},
             R"G(M117 homing G28 => rc=0 err=[] {{"method":"notify_status_update","params":[{"display_status":{"message":"homing G28"}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"M117 off M84"},
             R"G(M117 off M84 => rc=0 err=[] {{"method":"notify_status_update","params":[{"display_status":{"message":"off M84"}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},

            // --- positioning mode, homing, motors, moves ---------------------------
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G28"},
             R"G(G28 => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"xyz"}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G28 X"},
             R"G(G28 X => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"x"}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G28 y"},
             R"G(G28 y => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"y"}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G28 Z"},
             R"G(G28 Z => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"z"}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G28 X Y", "G28 Z"},
             R"G(G28 X Y => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"xy"}},0.0]}} ;; G28 Z => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"xyz"}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24, nullptr, nullptr, true, {"g28"}, R"G(g28 => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"xyz"}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"M84"},
             R"G(M84 => rc=0 err=[] {{"method":"notify_status_update","params":[{"stepper_enable":{"steppers":{"extruder":false,"stepper_x":false,"stepper_y":false,"stepper_z":false}},"toolhead":{"homed_axes":""}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G28", "M18"},
             R"G(G28 => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"xyz"}},0.0]}} ;; M18 => rc=0 err=[] {{"method":"notify_status_update","params":[{"stepper_enable":{"steppers":{"extruder":false,"stepper_x":false,"stepper_y":false,"stepper_z":false}},"toolhead":{"homed_axes":""}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G28", "M84", "G28 X"},
             R"G(G28 => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"xyz"}},0.0]}} ;; M84 => rc=0 err=[] {{"method":"notify_status_update","params":[{"stepper_enable":{"steppers":{"extruder":false,"stepper_x":false,"stepper_y":false,"stepper_z":false}},"toolhead":{"homed_axes":""}},0.0]}} ;; G28 X => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"x"}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G28", "G0 X10 Y20 Z5"},
             R"G(G28 => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"xyz"}},0.0]}} ;; G0 X10 Y20 Z5 => rc=0 err=[] {{"method":"notify_status_update","params":[{"motion_report":{"live_position":[10.0,20.0,5.0,0.0]},"toolhead":{"position":[10.0,20.0,5.0,0.0]}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G28", "G1 X10.5 Y 20 F3000 E5"},
             R"G(G28 => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"xyz"}},0.0]}} ;; G1 X10.5 Y 20 F3000 E5 => rc=0 err=[] {{"method":"notify_status_update","params":[{"motion_report":{"live_position":[10.5,20.0,0.0,0.0]},"toolhead":{"position":[10.5,20.0,0.0,0.0]}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G28", "G91", "G1 X10 Y20 Z1", "G1 X-5"},
             R"G(G28 => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"xyz"}},0.0]}} ;; G91 => rc=0 err=[] ;; G1 X10 Y20 Z1 => rc=0 err=[] {{"method":"notify_status_update","params":[{"motion_report":{"live_position":[10.0,20.0,1.0,0.0]},"toolhead":{"position":[10.0,20.0,1.0,0.0]}},0.0]}} ;; G1 X-5 => rc=0 err=[] {{"method":"notify_status_update","params":[{"motion_report":{"live_position":[5.0,20.0,1.0,0.0]},"toolhead":{"position":[5.0,20.0,1.0,0.0]}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G28", "G91", "G90", "G0 X7"},
             R"G(G28 => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"xyz"}},0.0]}} ;; G91 => rc=0 err=[] ;; G90 => rc=0 err=[] ;; G0 X7 => rc=0 err=[] {{"method":"notify_status_update","params":[{"motion_report":{"live_position":[7.0,0.0,0.0,0.0]},"toolhead":{"position":[7.0,0.0,0.0,0.0]}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G28", "G91 G90", "G0 X7"},
             R"G(G28 => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"xyz"}},0.0]}} ;; G91 G90 => rc=0 err=[] ;; G0 X7 => rc=0 err=[] {{"method":"notify_status_update","params":[{"motion_report":{"live_position":[7.0,0.0,0.0,0.0]},"toolhead":{"position":[7.0,0.0,0.0,0.0]}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G28", "G90 G91", "G0 X7"},
             R"G(G28 => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"xyz"}},0.0]}} ;; G90 G91 => rc=0 err=[] ;; G0 X7 => rc=0 err=[] {{"method":"notify_status_update","params":[{"motion_report":{"live_position":[7.0,0.0,0.0,0.0]},"toolhead":{"position":[7.0,0.0,0.0,0.0]}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G28", "G91", "SAVE_GCODE_STATE", "G90", "G0 X3", "RESTORE_GCODE_STATE", "G0 X1"},
             R"G(G28 => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"xyz"}},0.0]}} ;; G91 => rc=0 err=[] ;; SAVE_GCODE_STATE => rc=0 err=[] ;; G90 => rc=0 err=[] ;; G0 X3 => rc=0 err=[] {{"method":"notify_status_update","params":[{"motion_report":{"live_position":[3.0,0.0,0.0,0.0]},"toolhead":{"position":[3.0,0.0,0.0,0.0]}},0.0]}} ;; RESTORE_GCODE_STATE => rc=0 err=[] ;; G0 X1 => rc=0 err=[] {{"method":"notify_status_update","params":[{"motion_report":{"live_position":[4.0,0.0,0.0,0.0]},"toolhead":{"position":[4.0,0.0,0.0,0.0]}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G28", "G91", "SAVE_GCODE_STATE NAME=a G90", "RESTORE_GCODE_STATE NAME=a", "G0 X1"},
             R"G(G28 => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"xyz"}},0.0]}} ;; G91 => rc=0 err=[] ;; SAVE_GCODE_STATE NAME=a G90 => rc=0 err=[] ;; RESTORE_GCODE_STATE NAME=a => rc=0 err=[] ;; G0 X1 => rc=0 err=[] {{"method":"notify_status_update","params":[{"motion_report":{"live_position":[1.0,0.0,0.0,0.0]},"toolhead":{"position":[1.0,0.0,0.0,0.0]}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G28", "G0 X400"},
             R"G(G28 => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"xyz"}},0.0]}} ;; G0 X400 => rc=1 err=[Move out of range: X=400.000000] {{"method":"notify_gcode_response","params":["!! Move out of range: X=400.000000"]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G28", "G0 Y400"},
             R"G(G28 => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"xyz"}},0.0]}} ;; G0 Y400 => rc=1 err=[Move out of range: Y=400.000000] {{"method":"notify_gcode_response","params":["!! Move out of range: Y=400.000000"]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G28", "G0 Z400"},
             R"G(G28 => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"xyz"}},0.0]}} ;; G0 Z400 => rc=1 err=[Move out of range: Z=400.000000] {{"method":"notify_gcode_response","params":["!! Move out of range: Z=400.000000"]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G28", "G0 Z-1"},
             R"G(G28 => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"xyz"}},0.0]}} ;; G0 Z-1 => rc=1 err=[Move out of range: Z=-1.000000] {{"method":"notify_gcode_response","params":["!! Move out of range: Z=-1.000000"]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G28", "G91", "G0 X-1"},
             R"G(G28 => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"xyz"}},0.0]}} ;; G91 => rc=0 err=[] ;; G0 X-1 => rc=1 err=[Move out of range: X=-1.000000] {{"method":"notify_gcode_response","params":["!! Move out of range: X=-1.000000"]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G28", "G0 X400 Y400"},
             R"G(G28 => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"xyz"}},0.0]}} ;; G0 X400 Y400 => rc=1 err=[Move out of range: X=400.000000] {{"method":"notify_gcode_response","params":["!! Move out of range: X=400.000000"]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G28 G0 X5"},
             R"G(G28 G0 X5 => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"x"}},0.0]}} {{"method":"notify_status_update","params":[{"motion_report":{"live_position":[5.0,0.0,0.0,0.0]},"toolhead":{"position":[5.0,0.0,0.0,0.0]}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G0"},
             R"G(G0 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G0 Xabc"},
             R"G(G0 Xabc => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24, nullptr, nullptr, true, {"g1 x5"}, R"G(g1 x5 => rc=0 err=[] {{"method":"notify_status_update","params":[{"motion_report":{"live_position":[5.0,0.0,0.0,0.0]},"toolhead":{"position":[5.0,0.0,0.0,0.0]}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G10 P0"},
             R"G(G10 P0 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G92 E0"},
             R"G(G92 E0 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G92 X5"},
             R"G(G92 X5 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"G2 X5"},
             R"G(G2 X5 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},

            // --- tool change -----------------------------------------------------
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"T0"},
             R"G(T0 => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"extruder":"extruder"}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"T1"},
             R"G(T1 => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"extruder":"extruder1"}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"T12"},
             R"G(T12 => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"extruder":"extruder12"}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"T"},
             R"G(T => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"Tx"},
             R"G(Tx => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"t1"},
             R"G(t1 => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"extruder":"extruder1"}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"T1 S200"},
             R"G(T1 S200 => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"extruder":"extruder1"}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},

            // --- print control (async effects: synchronous half only) -------------
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"SDCARD_PRINT_FILE FILENAME=3DBenchy.gcode"},
             R"G(SDCARD_PRINT_FILE FILENAME=3DBenchy.gcode => rc=0 err=[] ;; klippy=0 phase=1 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"SDCARD_PRINT_FILE FILENAME=\"3DBenchy.gcode\""},
             R"G(SDCARD_PRINT_FILE FILENAME="3DBenchy.gcode" => rc=0 err=[] ;; klippy=0 phase=1 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"SDCARD_PRINT_FILE"},
             R"G(SDCARD_PRINT_FILE => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"SDCARD_PRINT_FILE FILENAME=3DBenchy.gcode", "PAUSE"},
             R"G(SDCARD_PRINT_FILE FILENAME=3DBenchy.gcode => rc=0 err=[] ;; PAUSE => rc=0 err=[] ;; klippy=0 phase=3 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"SDCARD_PRINT_FILE FILENAME=3DBenchy.gcode", "PAUSE", "RESUME"},
             R"G(SDCARD_PRINT_FILE FILENAME=3DBenchy.gcode => rc=0 err=[] ;; PAUSE => rc=0 err=[] ;; RESUME => rc=0 err=[] ;; klippy=0 phase=2 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"SDCARD_PRINT_FILE FILENAME=3DBenchy.gcode", "PAUSE foo=1"},
             R"G(SDCARD_PRINT_FILE FILENAME=3DBenchy.gcode => rc=0 err=[] ;; PAUSE foo=1 => rc=0 err=[] ;; klippy=0 phase=3 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"SDCARD_PRINT_FILE FILENAME=3DBenchy.gcode", "PAUSEX"},
             R"G(SDCARD_PRINT_FILE FILENAME=3DBenchy.gcode => rc=0 err=[] ;; PAUSEX => rc=0 err=[] ;; klippy=0 phase=1 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24, nullptr, nullptr, false, {"SDCARD_PRINT_FILE FILENAME=3DBenchy.gcode", "CANCEL_PRINT"}, R"G(SDCARD_PRINT_FILE FILENAME=3DBenchy.gcode => rc=0 err=[] ;; CANCEL_PRINT => rc=0 err=[] ;; klippy=0 phase=5 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"SDCARD_PRINT_FILE FILENAME=3DBenchy.gcode", "CANCEL_PRINT_X"},
             R"G(SDCARD_PRINT_FILE FILENAME=3DBenchy.gcode => rc=0 err=[] ;; CANCEL_PRINT_X => rc=0 err=[] ;; klippy=0 phase=1 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"SDCARD_PRINT_FILE FILENAME=3DBenchy.gcode", "pause"},
             R"G(SDCARD_PRINT_FILE FILENAME=3DBenchy.gcode => rc=0 err=[] ;; pause => rc=0 err=[] ;; klippy=0 phase=3 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"SDCARD_PRINT_FILE FILENAME=3DBenchy.gcode", "M112"},
             R"G(SDCARD_PRINT_FILE FILENAME=3DBenchy.gcode => rc=0 err=[] ;; M112 => rc=0 err=[] ;; klippy=0 phase=6 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"SDCARD_PRINT_FILE FILENAME=3DBenchy.gcode", "PAUSE M112"},
             R"G(SDCARD_PRINT_FILE FILENAME=3DBenchy.gcode => rc=0 err=[] ;; PAUSE M112 => rc=0 err=[] ;; klippy=0 phase=3 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"RESUME"},
             R"G(RESUME => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"M112"},
             R"G(M112 => rc=0 err=[] ;; klippy=0 phase=6 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},

            // --- fans ------------------------------------------------------------
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"M106 S128"},
             R"G(M106 S128 => rc=0 err=[] {{"method":"notify_status_update","params":[{"fan":{"speed":0.5019607843137255}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"M106 P1 S255"},
             R"G(M106 P1 S255 => rc=0 err=[] {{"method":"notify_status_update","params":[{"fan1":{"speed":1.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"M106 S300"},
             R"G(M106 S300 => rc=0 err=[] {{"method":"notify_status_update","params":[{"fan":{"speed":1.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"M106"},
             R"G(M106 => rc=0 err=[] {{"method":"notify_status_update","params":[{"fan":{"speed":0.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"M106 S100 M107"},
             R"G(M106 S100 M107 => rc=0 err=[] {{"method":"notify_status_update","params":[{"fan":{"speed":0.39215686274509803}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"M107"},
             R"G(M107 => rc=0 err=[] {{"method":"notify_status_update","params":[{"fan":{"speed":0.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"M107 P2"},
             R"G(M107 P2 => rc=0 err=[] {{"method":"notify_status_update","params":[{"fan2":{"speed":0.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_FAN_SPEED FAN=nevermore SPEED=0.5"},
             R"G(SET_FAN_SPEED FAN=nevermore SPEED=0.5 => rc=0 err=[] {{"method":"notify_status_update","params":[{"fan_generic nevermore":{"speed":0.5}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24, nullptr, nullptr, true, {"SET_FAN_SPEED FAN=nevermore SPEED=2"}, R"G(SET_FAN_SPEED FAN=nevermore SPEED=2 => rc=0 err=[] {{"method":"notify_status_update","params":[{"fan_generic nevermore":{"speed":1.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_FAN_SPEED SPEED=0.5"},
             R"G(SET_FAN_SPEED SPEED=0.5 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_FAN_SPEED FAN=nevermore"},
             R"G(SET_FAN_SPEED FAN=nevermore => rc=0 err=[] {{"method":"notify_status_update","params":[{"fan_generic nevermore":{"speed":0.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_FAN_SPEED FAN=fan SPEED=x"},
             R"G(SET_FAN_SPEED FAN=fan SPEED=x => rc=0 err=[] {{"method":"notify_status_update","params":[{"heater_fan hotend_fan":{"speed":0.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},

            // --- calibration, restart ---------------------------------------------
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"PID_CALIBRATE HEATER=extruder TARGET=200"},
             R"G(PID_CALIBRATE HEATER=extruder TARGET=200 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"PID_CALIBRATE HEATER=heater_bed TARGET=60 M104 S50"},
             R"G(PID_CALIBRATE HEATER=heater_bed TARGET=60 M104 S50 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"MPC_CALIBRATE HEATER=extruder FAN_BREAKPOINTS=2"},
             R"G(MPC_CALIBRATE HEATER=extruder FAN_BREAKPOINTS=2 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"MPC_CALIBRATE"},
             R"G(MPC_CALIBRATE => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"SAVE_CONFIG"},
             R"G(SAVE_CONFIG => rc=1 err=[Klippy Disconnected] ;; klippy=1 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"FIRMWARE_RESTART"},
             R"G(FIRMWARE_RESTART => rc=0 err=[] ;; klippy=1 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"RESTART"},
             R"G(RESTART => rc=0 err=[] ;; klippy=1 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"RESTART FIRMWARE"},
             R"G(RESTART FIRMWARE => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"SDCARD_PRINT_FILE FILENAME=3DBenchy.gcode", "RESTART"},
             R"G(SDCARD_PRINT_FILE FILENAME=3DBenchy.gcode => rc=0 err=[] ;; RESTART => rc=0 err=[] ;; klippy=1 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SHAPER_CALIBRATE AXIS=Y"},
             R"G(SHAPER_CALIBRATE AXIS=Y => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SHAPER_CALIBRATE AXIS=x"},
             R"G(SHAPER_CALIBRATE AXIS=x => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SHAPER_CALIBRATE"},
             R"G(SHAPER_CALIBRATE => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"TEST_RESONANCES AXIS=1,1 OUTPUT=resonances NAME=belt_a"},
             R"G(TEST_RESONANCES AXIS=1,1 OUTPUT=resonances NAME=belt_a => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"TEST_RESONANCES AXIS=X"},
             R"G(TEST_RESONANCES AXIS=X => rc=0 err=[] {{"method":"notify_gcode_response","params":["!! Unsupported axis"]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_INPUT_SHAPER SHAPER_FREQ_X=50"},
             R"G(SET_INPUT_SHAPER SHAPER_FREQ_X=50 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"MEASURE_AXES_NOISE"},
             R"G(MEASURE_AXES_NOISE => rc=0 err=[] {{"method":"notify_gcode_response","params":["Axes noise for xy-axis accelerometer: 12.345678 (x), 15.678901 (y), 8.234567 (z)"]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_PRESSURE_ADVANCE ADVANCE=0.05"},
             R"G(SET_PRESSURE_ADVANCE ADVANCE=0.05 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},

            // --- bed mesh --------------------------------------------------------
            {PT::VORON_24, nullptr, nullptr, true, {"BED_MESH_CALIBRATE"}, R"G(BED_MESH_CALIBRATE => rc=0 err=[] {{"method":"notify_status_update","params":[{"bed_mesh":{"mesh_max":[235.0,235.0],"mesh_min":[15.0,15.0],"mesh_params":{"algo":"lagrange"},"probed_matrix":"7x7","profile_name":"default","profiles":{"adaptive":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"},"default":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"}}}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=adaptive,default, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"BED_MESH_CALIBRATE PROFILE=foo"},
             R"G(BED_MESH_CALIBRATE PROFILE=foo => rc=0 err=[] {{"method":"notify_status_update","params":[{"bed_mesh":{"mesh_max":[235.0,235.0],"mesh_min":[15.0,15.0],"mesh_params":{"algo":"lagrange"},"probed_matrix":"7x7","profile_name":"foo","profiles":{"adaptive":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"},"default":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"},"foo":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"}}}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=foo profiles=adaptive,default,foo, tool=-1)G"},
            {PT::VORON_24, nullptr, nullptr, true, {"bed_mesh_calibrate profile=foo"}, R"G(bed_mesh_calibrate profile=foo => rc=0 err=[] {{"method":"notify_status_update","params":[{"bed_mesh":{"mesh_max":[235.0,235.0],"mesh_min":[15.0,15.0],"mesh_params":{"algo":"lagrange"},"probed_matrix":"7x7","profile_name":"default","profiles":{"adaptive":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"},"default":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"}}}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=adaptive,default, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"BED_MESH_PROFILE SAVE=a"},
             R"G(BED_MESH_PROFILE SAVE=a => rc=0 err=[] {{"method":"notify_status_update","params":[{"bed_mesh":{"mesh_max":[235.0,235.0],"mesh_min":[15.0,15.0],"mesh_params":{"algo":"lagrange"},"probed_matrix":"7x7","profile_name":"a","profiles":{"a":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"},"adaptive":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"},"default":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"}}}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=a profiles=a,adaptive,default, tool=-1)G"},
            {PT::VORON_24, nullptr, nullptr, true, {"BED_MESH_PROFILE SAVE=a", "BED_MESH_CLEAR", "BED_MESH_PROFILE LOAD=a"}, R"G(BED_MESH_PROFILE SAVE=a => rc=0 err=[] {{"method":"notify_status_update","params":[{"bed_mesh":{"mesh_max":[235.0,235.0],"mesh_min":[15.0,15.0],"mesh_params":{"algo":"lagrange"},"probed_matrix":"7x7","profile_name":"a","profiles":{"a":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"},"adaptive":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"},"default":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"}}}},0.0]}} ;; BED_MESH_CLEAR => rc=0 err=[] {{"method":"notify_status_update","params":[{"bed_mesh":{"mesh_max":[235.0,235.0],"mesh_min":[15.0,15.0],"mesh_params":{"algo":"lagrange"},"probed_matrix":"0x0","profile_name":"","profiles":{"a":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"},"adaptive":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"},"default":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"}}}},0.0]}} ;; BED_MESH_PROFILE LOAD=a => rc=0 err=[] {{"method":"notify_status_update","params":[{"bed_mesh":{"mesh_max":[235.0,235.0],"mesh_min":[15.0,15.0],"mesh_params":{"algo":"lagrange"},"probed_matrix":"7x7","profile_name":"a","profiles":{"a":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"},"adaptive":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"},"default":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"}}}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=a profiles=a,adaptive,default, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"BED_MESH_PROFILE LOAD=missing"},
             R"G(BED_MESH_PROFILE LOAD=missing => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"BED_MESH_PROFILE SAVE=a", "BED_MESH_PROFILE REMOVE=a"},
             R"G(BED_MESH_PROFILE SAVE=a => rc=0 err=[] {{"method":"notify_status_update","params":[{"bed_mesh":{"mesh_max":[235.0,235.0],"mesh_min":[15.0,15.0],"mesh_params":{"algo":"lagrange"},"probed_matrix":"7x7","profile_name":"a","profiles":{"a":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"},"adaptive":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"},"default":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"}}}},0.0]}} ;; BED_MESH_PROFILE REMOVE=a => rc=0 err=[] {{"method":"notify_status_update","params":[{"bed_mesh":{"mesh_max":[235.0,235.0],"mesh_min":[15.0,15.0],"mesh_params":{"algo":"lagrange"},"probed_matrix":"7x7","profile_name":"a","profiles":{"adaptive":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"},"default":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"}}}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=a profiles=adaptive,default, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"BED_MESH_PROFILE REMOVE=missing"},
             R"G(BED_MESH_PROFILE REMOVE=missing => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"BED_MESH_PROFILE"},
             R"G(BED_MESH_PROFILE => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"BED_MESH_PROFILE LOAD=a SAVE=b"},
             R"G(BED_MESH_PROFILE LOAD=a SAVE=b => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24, nullptr, nullptr, true, {"BED_MESH_CALIBRATE", "BED_MESH_CLEAR"}, R"G(BED_MESH_CALIBRATE => rc=0 err=[] {{"method":"notify_status_update","params":[{"bed_mesh":{"mesh_max":[235.0,235.0],"mesh_min":[15.0,15.0],"mesh_params":{"algo":"lagrange"},"probed_matrix":"7x7","profile_name":"default","profiles":{"adaptive":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"},"default":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"}}}},0.0]}} ;; BED_MESH_CLEAR => rc=0 err=[] {{"method":"notify_status_update","params":[{"bed_mesh":{"mesh_max":[235.0,235.0],"mesh_min":[15.0,15.0],"mesh_params":{"algo":"lagrange"},"probed_matrix":"0x0","profile_name":"","profiles":{"adaptive":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"},"default":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"}}}},0.0]}} ;; klippy=0 phase=0 excluded= mesh= profiles=adaptive,default, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"BED_MESH_CALIBRATE BED_MESH_CLEAR"},
             R"G(BED_MESH_CALIBRATE BED_MESH_CLEAR => rc=0 err=[] {{"method":"notify_status_update","params":[{"bed_mesh":{"mesh_max":[235.0,235.0],"mesh_min":[15.0,15.0],"mesh_params":{"algo":"lagrange"},"probed_matrix":"7x7","profile_name":"default","profiles":{"adaptive":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"},"default":{"mesh_params":{"max_x":235.0,"max_y":235.0,"min_x":15.0,"min_y":15.0,"x_count":7,"y_count":7},"points":"7x7"}}}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=adaptive,default, tool=-1)G"},

            // --- offsets ---------------------------------------------------------
            {PT::VORON_24, nullptr, nullptr, true, {"SET_GCODE_OFFSET Z=0.2"}, R"G(SET_GCODE_OFFSET Z=0.2 => rc=0 err=[] {{"method":"notify_status_update","params":[{"gcode_move":{"extrude_factor":1.0,"gcode_position":[0.0,0.0,0.0,0.0],"homing_origin":[0.0,0.0,0.2,0.0],"speed_factor":1.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_GCODE_OFFSET Z=0.2", "SET_GCODE_OFFSET Z_ADJUST=-0.05"},
             R"G(SET_GCODE_OFFSET Z=0.2 => rc=0 err=[] {{"method":"notify_status_update","params":[{"gcode_move":{"extrude_factor":1.0,"gcode_position":[0.0,0.0,0.0,0.0],"homing_origin":[0.0,0.0,0.2,0.0],"speed_factor":1.0}},0.0]}} ;; SET_GCODE_OFFSET Z_ADJUST=-0.05 => rc=0 err=[] {{"method":"notify_status_update","params":[{"gcode_move":{"extrude_factor":1.0,"gcode_position":[0.0,0.0,0.0,0.0],"homing_origin":[0.0,0.0,0.15000000000000002,0.0],"speed_factor":1.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_GCODE_OFFSET Z=0.3 Z_ADJUST=0.1"},
             R"G(SET_GCODE_OFFSET Z=0.3 Z_ADJUST=0.1 => rc=0 err=[] {{"method":"notify_status_update","params":[{"gcode_move":{"extrude_factor":1.0,"gcode_position":[0.0,0.0,0.0,0.0],"homing_origin":[0.0,0.0,0.3,0.0],"speed_factor":1.0}},0.0]}} {{"method":"notify_status_update","params":[{"gcode_move":{"extrude_factor":1.0,"gcode_position":[0.0,0.0,0.0,0.0],"homing_origin":[0.0,0.0,0.4,0.0],"speed_factor":1.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_GCODE_OFFSET Z=abc"},
             R"G(SET_GCODE_OFFSET Z=abc => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_GCODE_OFFSET X=1"},
             R"G(SET_GCODE_OFFSET X=1 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_TOOL_PARAMETER T=1 PARAMETER=gcode_x_offset VALUE=-0.05"},
             R"G(SET_TOOL_PARAMETER T=1 PARAMETER=gcode_x_offset VALUE=-0.05 => rc=0 err=[] {{"method":"notify_status_update","params":[{"tool T1":{"gcode_x_offset":-0.05}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_TOOL_PARAMETER T=1 PARAMETER=bogus VALUE=1"},
             R"G(SET_TOOL_PARAMETER T=1 PARAMETER=bogus VALUE=1 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_TOOL_PARAMETER T=1 PARAMETER=gcode_x_offset"},
             R"G(SET_TOOL_PARAMETER T=1 PARAMETER=gcode_x_offset => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24, nullptr, nullptr, true, {"SET_TOOL_PARAMETER T=1 PARAMETER=gcode_z_offset VALUE=0.2", "SAVE_TOOL_PARAMETER T=1 PARAMETER=gcode_z_offset"}, R"G(SET_TOOL_PARAMETER T=1 PARAMETER=gcode_z_offset VALUE=0.2 => rc=0 err=[] {{"method":"notify_status_update","params":[{"tool T1":{"gcode_z_offset":0.2}},0.0]}} ;; SAVE_TOOL_PARAMETER T=1 PARAMETER=gcode_z_offset => rc=0 err=[] {{"method":"notify_status_update","params":[{"configfile":{"save_config_pending":true,"save_config_pending_items":{"tool T1":{"gcode_z_offset":"0.2"}}}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SAVE_TOOL_PARAMETER T=1"},
             R"G(SAVE_TOOL_PARAMETER T=1 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},

            // --- LEDs ------------------------------------------------------------
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_LED LED=chamber_light RED=1 GREEN=0.5 BLUE=0"},
             R"G(SET_LED LED=chamber_light RED=1 GREEN=0.5 BLUE=0 => rc=0 err=[] {{"method":"notify_status_update","params":[{"led caselight":{"color_data":[[0.0,0.0,0.0,0.0]]},"neopixel chamber_light":{"color_data":[[1.0,0.5,0.0,0.0]]},"neopixel status_led":{"color_data":[[0.0,0.0,0.0,0.0]]}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_LED LED=\"chamber_light\" RED=2 WHITE=1"},
             R"G(SET_LED LED="chamber_light" RED=2 WHITE=1 => rc=0 err=[] {{"method":"notify_status_update","params":[{"led caselight":{"color_data":[[0.0,0.0,0.0,0.0]]},"neopixel chamber_light":{"color_data":[[1.0,0.0,0.0,1.0]]},"neopixel status_led":{"color_data":[[0.0,0.0,0.0,0.0]]}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_LED LED=nope RED=1"},
             R"G(SET_LED LED=nope RED=1 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_LED RED=1"},
             R"G(SET_LED RED=1 => rc=0 err=[] {{"method":"notify_status_update","params":[{"led caselight":{"color_data":[[0.0,0.0,0.0,0.0]]},"neopixel chamber_light":{"color_data":[[1.0,0.0,0.0,0.0]]},"neopixel status_led":{"color_data":[[0.0,0.0,0.0,0.0]]}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24, nullptr, nullptr, true, {"SET_LED_EFFECT EFFECT=rainbow"}, R"G(SET_LED_EFFECT EFFECT=rainbow => rc=0 err=[] {{"method":"notify_status_update","params":[{"led caselight":{"color_data":[[0.0,0.0,0.0,0.0]]},"neopixel chamber_light":{"color_data":[[0.0,0.0,0.0,0.0]]},"neopixel status_led":{"color_data":[[0.0,0.0,0.0,0.0]]}},0.0]}} {{"method":"notify_status_update","params":[{"led caselight":{"color_data":[[0.5,0.0,1.0,0.0]]},"led_effect breathing":{"enabled":false},"led_effect fire_comet":{"enabled":false},"led_effect rainbow":{"enabled":true},"led_effect static_white":{"enabled":false},"neopixel chamber_light":{"color_data":[[0.5,0.0,1.0,0.0]]},"neopixel status_led":{"color_data":[[0.5,0.0,1.0,0.0]]}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_LED_EFFECT EFFECT=unknown"},
             R"G(SET_LED_EFFECT EFFECT=unknown => rc=0 err=[] {{"method":"notify_status_update","params":[{"led caselight":{"color_data":[[0.0,0.0,0.0,0.0]]},"neopixel chamber_light":{"color_data":[[0.0,0.0,0.0,0.0]]},"neopixel status_led":{"color_data":[[0.0,0.0,0.0,0.0]]}},0.0]}} {{"method":"notify_status_update","params":[{"led_effect breathing":{"enabled":false},"led_effect fire_comet":{"enabled":false},"led_effect rainbow":{"enabled":false},"led_effect static_white":{"enabled":false},"led_effect unknown":{"enabled":true}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_LED_EFFECT EFFECT=rainbow STOP=1"},
             R"G(SET_LED_EFFECT EFFECT=rainbow STOP=1 => rc=0 err=[] {{"method":"notify_status_update","params":[{"led caselight":{"color_data":[[0.0,0.0,0.0,0.0]]},"neopixel chamber_light":{"color_data":[[0.0,0.0,0.0,0.0]]},"neopixel status_led":{"color_data":[[0.0,0.0,0.0,0.0]]}},0.0]}} {{"method":"notify_status_update","params":[{"led_effect rainbow":{"enabled":false}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SET_LED_EFFECT"},
             R"G(SET_LED_EFFECT => rc=0 err=[] {{"method":"notify_status_update","params":[{"led caselight":{"color_data":[[0.0,0.0,0.0,0.0]]},"neopixel chamber_light":{"color_data":[[0.0,0.0,0.0,0.0]]},"neopixel status_led":{"color_data":[[0.0,0.0,0.0,0.0]]}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"STOP_LED_EFFECTS"},
             R"G(STOP_LED_EFFECTS => rc=0 err=[] {{"method":"notify_status_update","params":[{"led caselight":{"color_data":[[0.0,0.0,0.0,0.0]]},"led_effect breathing":{"enabled":false},"led_effect fire_comet":{"enabled":false},"led_effect rainbow":{"enabled":false},"led_effect static_white":{"enabled":false},"neopixel chamber_light":{"color_data":[[0.0,0.0,0.0,0.0]]},"neopixel status_led":{"color_data":[[0.0,0.0,0.0,0.0]]}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},

            // --- manual probe ----------------------------------------------------
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"PROBE_CALIBRATE"},
             R"G(PROBE_CALIBRATE => rc=0 err=[] {{"method":"notify_status_update","params":[{"manual_probe":{"is_active":true,"z_position":5.0,"z_position_lower":null,"z_position_upper":null}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"Z_ENDSTOP_CALIBRATE"},
             R"G(Z_ENDSTOP_CALIBRATE => rc=0 err=[] {{"method":"notify_status_update","params":[{"manual_probe":{"is_active":true,"z_position":5.0,"z_position_lower":null,"z_position_upper":null}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"PROBE_CALIBRATE", "PROBE_CALIBRATE"},
             R"G(PROBE_CALIBRATE => rc=0 err=[] {{"method":"notify_status_update","params":[{"manual_probe":{"is_active":true,"z_position":5.0,"z_position_lower":null,"z_position_upper":null}},0.0]}} ;; PROBE_CALIBRATE => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"PROBE_CALIBRATE Z_ENDSTOP_CALIBRATE"},
             R"G(PROBE_CALIBRATE Z_ENDSTOP_CALIBRATE => rc=0 err=[] {{"method":"notify_status_update","params":[{"manual_probe":{"is_active":true,"z_position":5.0,"z_position_lower":null,"z_position_upper":null}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"TESTZ Z=1"},
             R"G(TESTZ Z=1 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"TESTZ Z=1 EXCLUDE_OBJECT NAME=a"},
             R"G(TESTZ Z=1 EXCLUDE_OBJECT NAME=a => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"PROBE_CALIBRATE", "TESTZ Z=+0.1"},
             R"G(PROBE_CALIBRATE => rc=0 err=[] {{"method":"notify_status_update","params":[{"manual_probe":{"is_active":true,"z_position":5.0,"z_position_lower":null,"z_position_upper":null}},0.0]}} ;; TESTZ Z=+0.1 => rc=0 err=[] {{"method":"notify_status_update","params":[{"manual_probe":{"is_active":true,"z_position":5.1,"z_position_lower":null,"z_position_upper":null}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"PROBE_CALIBRATE", "TESTZ Z=-0.05"},
             R"G(PROBE_CALIBRATE => rc=0 err=[] {{"method":"notify_status_update","params":[{"manual_probe":{"is_active":true,"z_position":5.0,"z_position_lower":null,"z_position_upper":null}},0.0]}} ;; TESTZ Z=-0.05 => rc=0 err=[] {{"method":"notify_status_update","params":[{"manual_probe":{"is_active":true,"z_position":4.95,"z_position_lower":null,"z_position_upper":null}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"PROBE_CALIBRATE", "TESTZ Z=0.3"},
             R"G(PROBE_CALIBRATE => rc=0 err=[] {{"method":"notify_status_update","params":[{"manual_probe":{"is_active":true,"z_position":5.0,"z_position_lower":null,"z_position_upper":null}},0.0]}} ;; TESTZ Z=0.3 => rc=0 err=[] {{"method":"notify_status_update","params":[{"manual_probe":{"is_active":true,"z_position":0.3,"z_position_lower":null,"z_position_upper":null}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"PROBE_CALIBRATE", "TESTZ Z=50"},
             R"G(PROBE_CALIBRATE => rc=0 err=[] {{"method":"notify_status_update","params":[{"manual_probe":{"is_active":true,"z_position":5.0,"z_position_lower":null,"z_position_upper":null}},0.0]}} ;; TESTZ Z=50 => rc=0 err=[] {{"method":"notify_status_update","params":[{"manual_probe":{"is_active":true,"z_position":10.0,"z_position_lower":null,"z_position_upper":null}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"PROBE_CALIBRATE", "TESTZ Z=abc"},
             R"G(PROBE_CALIBRATE => rc=0 err=[] {{"method":"notify_status_update","params":[{"manual_probe":{"is_active":true,"z_position":5.0,"z_position_lower":null,"z_position_upper":null}},0.0]}} ;; TESTZ Z=abc => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"PROBE_CALIBRATE", "TESTZ"},
             R"G(PROBE_CALIBRATE => rc=0 err=[] {{"method":"notify_status_update","params":[{"manual_probe":{"is_active":true,"z_position":5.0,"z_position_lower":null,"z_position_upper":null}},0.0]}} ;; TESTZ => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"PROBE_CALIBRATE", "ACCEPT"},
             R"G(PROBE_CALIBRATE => rc=0 err=[] {{"method":"notify_status_update","params":[{"manual_probe":{"is_active":true,"z_position":5.0,"z_position_lower":null,"z_position_upper":null}},0.0]}} ;; ACCEPT => rc=0 err=[] {{"method":"notify_status_update","params":[{"manual_probe":{"is_active":false,"z_position":5.0,"z_position_lower":null,"z_position_upper":null}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"PROBE_CALIBRATE", "ACCEPT now"},
             R"G(PROBE_CALIBRATE => rc=0 err=[] {{"method":"notify_status_update","params":[{"manual_probe":{"is_active":true,"z_position":5.0,"z_position_lower":null,"z_position_upper":null}},0.0]}} ;; ACCEPT now => rc=0 err=[] {{"method":"notify_status_update","params":[{"manual_probe":{"is_active":false,"z_position":5.0,"z_position_lower":null,"z_position_upper":null}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"PROBE_CALIBRATE", "ACCEPTX"},
             R"G(PROBE_CALIBRATE => rc=0 err=[] {{"method":"notify_status_update","params":[{"manual_probe":{"is_active":true,"z_position":5.0,"z_position_lower":null,"z_position_upper":null}},0.0]}} ;; ACCEPTX => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"ACCEPT"},
             R"G(ACCEPT => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"PROBE_CALIBRATE", "ABORT"},
             R"G(PROBE_CALIBRATE => rc=0 err=[] {{"method":"notify_status_update","params":[{"manual_probe":{"is_active":true,"z_position":5.0,"z_position_lower":null,"z_position_upper":null}},0.0]}} ;; ABORT => rc=0 err=[] {{"method":"notify_status_update","params":[{"manual_probe":{"is_active":false,"z_position":5.0,"z_position_lower":null,"z_position_upper":null}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"PROBE_CALIBRATE", "ABORT now"},
             R"G(PROBE_CALIBRATE => rc=0 err=[] {{"method":"notify_status_update","params":[{"manual_probe":{"is_active":true,"z_position":5.0,"z_position_lower":null,"z_position_upper":null}},0.0]}} ;; ABORT now => rc=0 err=[] {{"method":"notify_status_update","params":[{"manual_probe":{"is_active":false,"z_position":5.0,"z_position_lower":null,"z_position_upper":null}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"ABORT"},
             R"G(ABORT => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"PROBE"},
             R"G(PROBE => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"PROBE_ACCURACY"},
             R"G(PROBE_ACCURACY => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"QUAD_GANTRY_LEVEL"},
             R"G(QUAD_GANTRY_LEVEL => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"Z_TILT_ADJUST"},
             R"G(Z_TILT_ADJUST => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"QUAD_GANTRY_LEVEL Z_TILT_ADJUST"},
             R"G(QUAD_GANTRY_LEVEL Z_TILT_ADJUST => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},

            // --- exclude object --------------------------------------------------
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"EXCLUDE_OBJECT NAME=Part_1"},
             R"G(EXCLUDE_OBJECT NAME=Part_1 => rc=0 err=[] {{"method":"notify_status_update","params":[{"exclude_object":{"current_object":null,"excluded_objects":["Part_1"]}},0.0]}} ;; klippy=0 phase=0 excluded=Part_1, mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24, nullptr, nullptr, true, {"EXCLUDE_OBJECT NAME=\"Part With Spaces\""}, R"G(EXCLUDE_OBJECT NAME="Part With Spaces" => rc=0 err=[] {{"method":"notify_status_update","params":[{"exclude_object":{"current_object":null,"excluded_objects":["Part With Spaces"]}},0.0]}} ;; klippy=0 phase=0 excluded=Part With Spaces, mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"EXCLUDE_OBJECT NAME=a", "EXCLUDE_OBJECT NAME=b"},
             R"G(EXCLUDE_OBJECT NAME=a => rc=0 err=[] {{"method":"notify_status_update","params":[{"exclude_object":{"current_object":null,"excluded_objects":["a"]}},0.0]}} ;; EXCLUDE_OBJECT NAME=b => rc=0 err=[] {{"method":"notify_status_update","params":[{"exclude_object":{"current_object":null,"excluded_objects":["a","b"]}},0.0]}} ;; klippy=0 phase=0 excluded=a,b, mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"EXCLUDE_OBJECT"},
             R"G(EXCLUDE_OBJECT => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"EXCLUDE_OBJECT NAME="},
             R"G(EXCLUDE_OBJECT NAME= => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"EXCLUDE_OBJECT_DEFINE NAME=a"},
             R"G(EXCLUDE_OBJECT_DEFINE NAME=a => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"EXCLUDE_OBJECT_START NAME=a"},
             R"G(EXCLUDE_OBJECT_START NAME=a => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"EXCLUDE_OBJECT_END NAME=a"},
             R"G(EXCLUDE_OBJECT_END NAME=a => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},

            // --- vendor personas -------------------------------------------------
            {PT::VORON_24,
             "medusahc",
             nullptr,
             false,
             {"OPEN"},
             R"G(OPEN => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             "medusahc",
             nullptr,
             false,
             {"CLOSE"},
             R"G(CLOSE => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             "medusahc",
             nullptr,
             false,
             {"MHC_OPEN"},
             R"G(MHC_OPEN => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             "medusahc",
             nullptr,
             false,
             {"MHC_CLOSE"},
             R"G(MHC_CLOSE => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             "medusahc",
             nullptr,
             false,
             {"SELECT_TOOL T=2"},
             R"G(SELECT_TOOL T=2 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             "medusahc",
             nullptr,
             false,
             {"SELECT_TOOL"},
             R"G(SELECT_TOOL => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             "medusahc",
             nullptr,
             false,
             {"UNSELECT_TOOL"},
             R"G(UNSELECT_TOOL => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             "medusahc",
             nullptr,
             false,
             {"DROP_TOOL"},
             R"G(DROP_TOOL => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             "medusahc",
             nullptr,
             false,
             {"T1"},
             R"G(T1 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             "medusahc",
             nullptr,
             false,
             {"OPENX"},
             R"G(OPENX => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             "medusahc",
             nullptr,
             false,
             {"T"},
             R"G(T => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"OPEN"},
             R"G(OPEN => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"SELECT_TOOL T=2"},
             R"G(SELECT_TOOL T=2 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::FLASHFORGE_CREATOR5_ZMOD,
             nullptr,
             nullptr,
             true,
             {"_T_IN T=2"},
             R"G(_T_IN T=2 => rc=0 err=[] {{"method":"notify_status_update","params":[{"zmod_color":{"active_tool_id":2}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::FLASHFORGE_CREATOR5_ZMOD,
             nullptr,
             nullptr,
             true,
             {"_T_IN T=9"},
             R"G(_T_IN T=9 => rc=1 err=[T out of range: 9] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::FLASHFORGE_CREATOR5_ZMOD,
             nullptr,
             nullptr,
             true,
             {"_T_IN"},
             R"G(_T_IN => rc=1 err=[T out of range: ] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::FLASHFORGE_CREATOR5_ZMOD,
             nullptr,
             nullptr,
             true,
             {"_T_IN T=1", "_T_OUT"},
             R"G(_T_IN T=1 => rc=0 err=[] {{"method":"notify_status_update","params":[{"zmod_color":{"active_tool_id":1}},0.0]}} ;; _T_OUT => rc=0 err=[] {{"method":"notify_status_update","params":[{"zmod_color":{"active_tool_id":-1}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::FLASHFORGE_CREATOR5_ZMOD, nullptr, nullptr, true, {"CHANGE_ZCOLOR SLOT=1 TYPE=PLA HEX=ff0000"}, R"G(CHANGE_ZCOLOR SLOT=1 TYPE=PLA HEX=ff0000 => rc=0 err=[] {{"method":"notify_status_update","params":[{"zmod_color":{"slots":[{"HEX":"FFFFFF","ID":"1","Material":"PLA"},{"HEX":"0ACC38","ID":"2","Material":"PETG"},{"HEX":"161616","ID":"3","Material":"ABS"},{"HEX":"F72224","ID":"4","Material":"PLA"}]}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::FLASHFORGE_CREATOR5_ZMOD,
             nullptr,
             nullptr,
             true,
             {"CHANGE_ZCOLOR SLOT=2 TYPE=PLA HEX=123456"},
             R"G(CHANGE_ZCOLOR SLOT=2 TYPE=PLA HEX=123456 => rc=0 err=[] {{"method":"notify_status_update","params":[{"zmod_color":{"slots":[{"HEX":"FFFFFF","ID":"1","Material":"PLA"},{"HEX":"FFFFFF","ID":"2","Material":"PLA"},{"HEX":"161616","ID":"3","Material":"ABS"},{"HEX":"F72224","ID":"4","Material":"PLA"}]}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::FLASHFORGE_CREATOR5_ZMOD,
             nullptr,
             nullptr,
             true,
             {"CHANGE_ZCOLOR SLOT=1 TYPE=NOPE HEX=ff0000"},
             R"G(CHANGE_ZCOLOR SLOT=1 TYPE=NOPE HEX=ff0000 => rc=1 err=[Unknown material type: NOPE] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::FLASHFORGE_CREATOR5_ZMOD,
             nullptr,
             nullptr,
             true,
             {"CHANGE_ZCOLOR SLOT=7 TYPE=PLA HEX=ff0000"},
             R"G(CHANGE_ZCOLOR SLOT=7 TYPE=PLA HEX=ff0000 => rc=1 err=[SLOT out of range: 7] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::FLASHFORGE_CREATOR5_ZMOD,
             nullptr,
             nullptr,
             true,
             {"CHANGE_ZCOLOR"},
             R"G(CHANGE_ZCOLOR => rc=1 err=[Unknown material type: ] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::FLASHFORGE_CREATOR5_ZMOD,
             nullptr,
             nullptr,
             true,
             {"_T_IN2 T=1"},
             R"G(_T_IN2 T=1 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"_T_IN T=2"},
             R"G(_T_IN T=2 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::CREALITY_K1_MAX,
             "cfs",
             nullptr,
             false,
             {"BOX_FIND_CUT_POS"},
             R"G(BOX_FIND_CUT_POS => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::CREALITY_K1_MAX,
             "cfs",
             nullptr,
             true,
             {"BOX_CUSTOM_COMMAND CMD=XYZ_ZERO"},
             R"G(BOX_CUSTOM_COMMAND CMD=XYZ_ZERO => rc=0 err=[] {{"method":"notify_status_update","params":[{"motion_report":{"live_position":[184.5,291.5,0.0,0.0]},"toolhead":{"homed_axes":"xyz","position":[184.5,291.5,0.0,0.0]}},0.0]}} {{"method":"notify_gcode_response","params":["x_park = 184.50"]}} {{"method":"notify_gcode_response","params":["y_park = 291.50"]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::CREALITY_K1_MAX,
             "cfs",
             nullptr,
             true,
             {"BOX_CUSTOM_COMMAND CMD=Y_SAFE"},
             R"G(BOX_CUSTOM_COMMAND CMD=Y_SAFE => rc=0 err=[] {{"method":"notify_status_update","params":[{"motion_report":{"live_position":[0.0,291.5,0.0,0.0]},"toolhead":{"homed_axes":"xyz","position":[0.0,291.5,0.0,0.0]}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::CREALITY_K1_MAX, "cfs", nullptr, true, {"BOX_CUSTOM_COMMAND CMD=COORDINATES_ADJUST_PREPARE"}, R"G(BOX_CUSTOM_COMMAND CMD=COORDINATES_ADJUST_PREPARE => rc=0 err=[] {{"method":"notify_status_update","params":[{"motion_report":{"live_position":[184.5,291.5,0.0,0.0]},"toolhead":{"homed_axes":"xyz","position":[184.5,291.5,0.0,0.0]}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::CREALITY_K1_MAX,
             "cfs",
             nullptr,
             true,
             {"BOX_CUSTOM_COMMAND CMD=COORDINATES_ADJUST_SAVE_POS"},
             R"G(BOX_CUSTOM_COMMAND CMD=COORDINATES_ADJUST_SAVE_POS => rc=0 err=[] {{"method":"notify_gcode_response","params":["cmd_save_extrude_pos x=0.00 y=0.00"]}} {{"method":"notify_gcode_response","params":["MODIFY_BOX_CFG: success, extrude_pos_x=0.0,"]}} {{"method":"notify_gcode_response","params":["SAVE_BOX_CFG ok: extrude_pos_x=0.0,extrude_pos_y=0.0"]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::CREALITY_K1_MAX,
             "cfs",
             nullptr,
             true,
             {"BOX_CUSTOM_COMMAND CMD=UNKNOWN"},
             R"G(BOX_CUSTOM_COMMAND CMD=UNKNOWN => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::CREALITY_K1_MAX,
             "cfs",
             nullptr,
             true,
             {"BOX_CUSTOM_COMMAND"},
             R"G(BOX_CUSTOM_COMMAND => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"BOX_FIND_CUT_POS"},
             R"G(BOX_FIND_CUT_POS => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"BOX_CUSTOM_COMMAND CMD=XYZ_ZERO"},
             R"G(BOX_CUSTOM_COMMAND CMD=XYZ_ZERO => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"AUTO_FEEDING EXTRUDER=1 LOAD=1"},
             R"G(AUTO_FEEDING EXTRUDER=1 LOAD=1 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"AUTO_FEEDING EXTRUDER=1 UNLOAD=1"},
             R"G(AUTO_FEEDING EXTRUDER=1 UNLOAD=1 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"AUTO_FEEDING_BATCH ACTION=START"},
             R"G(AUTO_FEEDING_BATCH ACTION=START => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"AUTO_FEEDING EXTRUDER=9"},
             R"G(AUTO_FEEDING EXTRUDER=9 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             false,
             {"AUTO_FEEDING EXTRUDER=1 M104 S200"},
             R"G(AUTO_FEEDING EXTRUDER=1 M104 S200 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             "ifs-module",
             nullptr,
             true,
             {"IFS_SET_MATERIAL SLOT=1 TYPE=PLA"},
             R"G(IFS_SET_MATERIAL SLOT=1 TYPE=PLA => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             "ifs-module",
             nullptr,
             false,
             {"IFS_LOAD SLOT=1"},
             R"G(IFS_LOAD SLOT=1 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             "ifs-module",
             nullptr,
             false,
             {"IFS_SELECT SLOT=2"},
             R"G(IFS_SELECT SLOT=2 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             "ifs-module",
             nullptr,
             false,
             {"IFS_UNLOAD"},
             R"G(IFS_UNLOAD => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             "ifs-module",
             nullptr,
             false,
             {"IFS_EJECT"},
             R"G(IFS_EJECT => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             "ifs-module",
             nullptr,
             true,
             {"T1"},
             R"G(T1 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             "ifs-module",
             nullptr,
             true,
             {"M104 S200"},
             R"G(M104 S200 => rc=0 err=[] {{"method":"notify_status_update","params":[{"extruder":{"target":200.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"IFS_LOAD SLOT=1"},
             R"G(IFS_LOAD SLOT=1 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},

            // --- unrecognised ----------------------------------------------------
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {""},
             R"G( => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"   "},
             R"G(    => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24,
             nullptr,
             nullptr,
             true,
             {"FOO_BAR BAZ=1"},
             R"G(FOO_BAR BAZ=1 => rc=0 err=[] ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
            {PT::VORON_24, nullptr, nullptr, true, {"G28", "M117 done", "M104 S0"}, R"G(G28 => rc=0 err=[] {{"method":"notify_status_update","params":[{"toolhead":{"homed_axes":"xyz"}},0.0]}} ;; M117 done => rc=0 err=[] {{"method":"notify_status_update","params":[{"display_status":{"message":"done"}},0.0]}} ;; M104 S0 => rc=0 err=[] {{"method":"notify_status_update","params":[{"extruder":{"target":0.0}},0.0]}} ;; klippy=0 phase=0 excluded= mesh=default profiles=default,adaptive, tool=-1)G"},
        };
    return rows;
}

} // namespace

TEST_CASE_METHOD(LVGLTestFixture, "gcode_script dispatch is pinned per command",
                 "[mock][gcode_dispatch]") {
    const auto& rows = cases();
    for (size_t i = 0; i < rows.size(); ++i) {
        INFO("row " << i << ": " << rows[i].scripts.front());
        CHECK(snapshot(rows[i]) == std::string(rows[i].expected));
    }
}
